task :default => "C:build"

namespace :C do

  task :check do
    `which cc`
    raise "Please ensure that you have a C compiler installed" unless $?.success?
  end

  task :clean do
    path = File.dirname(File.expand_path(__FILE__))
    `cd #{path}; rm -f romanize`
    `cd #{path}; rm -f deromanize`
  end

  task :build do
    path = File.dirname(File.expand_path(__FILE__))
    `cd #{path}; cc -o ./romanize ./romanize.c`
    `cd #{path}; cc -o ./deromanize ./deromanize.c`
  end
end
