#!/usr/bin/env node

'use strict';

var romanNumber = process.argv[2];

if (!romanNumber) {
  process.exit(1);
}

var valueMap = {
  I: 1,
  V: 5,
  X: 10,
  L: 50,
  C: 100,
  D: 500,
  M: 1000
};

var deromanized = 0;
var lastValue = 0;

romanNumber.split('').reverse().forEach(function (char) {
  var value = valueMap[char];
  deromanized += value >= lastValue ? value : -value;
  lastValue = value;
});

console.log(deromanized);
