namespace :OCaml do
  task :clean do
    path = File.dirname(__FILE__)
    `cd #{path}; rm -f romanize deromanize *.cmi *.cmo`
  end

  task :check do
    `which ocaml`

    unless $?.success?
      raise "ocaml not installed, please run `brew install ocaml`"
    end

    `which opam`

    unless $?.success?
      raise "opam not installed, please run `brew install opam`"
    end

    `which ocamlfind`

    unless $?.success?
      raise "ocamlfind not installed, please run `opam install ocamlfind`"
    end

    `ocamlfind query Batteries`

    unless $?.success?
      raise "Batteries not installed, please run `opam install Batteries`"
    end
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    `cd #{path}; ocamlfind ocamlc -package batteries -linkpkg -o romanize romanize.ml`
    `cd #{path}; ocamlfind ocamlc -package batteries -linkpkg -o deromanize deromanize.ml`
  end
end

task :default => 'OCaml:build'
