#!/usr/bin/env ruby

input  = ARGV.last
number = input.to_i
output = ""

def convert(digit, one_char, five_char, ten_char)
  if digit < 4
    one_char * digit
  elsif digit == 4
    one_char + five_char
  elsif digit < 9
    five_char + (one_char * (digit - 5))
  elsif digit == 9
    one_char + ten_char
  end
end

def one_five_ten_for(place)
  {
    0 => ["I", "V", "X"],
    1 => ["X", "L", "C"],
    2 => ["C", "D", "M"],
    3 => ["M",  "",  ""]
  }[place]
end

input.length.times do |i|
  digit  = number.modulo(10)
  number = number / 10
  output.prepend convert(digit, *one_five_ten_for(i))
end

print output
