namespace :PHP do
  task :check do
    `which composer`
    raise "Please ensure that you have composer installed. See https://getcomposer.org/" unless $?.success?
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    puts `cd #{path}; composer install;`
    puts "Depencies installed! You may now run `php romanize 199` and `php deromanize LXXIII`"
  end

  task :test => :check do
    path = File.dirname(__FILE__)
    puts `cd #{path}; vendor/phpspec/phpspec/bin/phpspec run --format=pretty`
  end
end
